# Generated by Django 5.2.5 on 2025-08-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifyuser",
            name="access_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
